version: "3"

vars:
  HUGO: hugo

tasks:
  run:
    desc: Run Hugo server with drafts
    cmds:
      - "{{.HUGO}} server -D --bind=0.0.0.0"

  dev:
    desc: Run Hugo server with drafts and disable fast render
    cmds:
      - "{{.HUGO}} server -D --bind=0.0.0.0 --disableFastRender"

  build:
    desc: Build Hugo site
    cmds:
      - "{{.HUGO}} --gc --minify"

  new:
    desc: "Create a new post (usage: task new -- my-post-title)"
    cmds:
      - "{{.HUGO}} new post/$(date +%Y)/$(date +%Y-%m-%d)-{{.CLI_ARGS}}.md"
